# Generated by Django 4.1.7 on 2023-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todoaction',
            constraint=models.UniqueConstraint(fields=('to_do_list', 'title'), name='unique title for each to-do list'),
        ),
        migrations.AddConstraint(
            model_name='todolist',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique title for each user'),
        ),
    ]
