# Generated by Django 4.1.7 on 2023-03-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoaction_unique title for each to-do list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoaction',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoaction',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='todo.todolist'),
        ),
    ]
